### ISSUE TITLE
FYI on a known build issue: error: failed to load source for dependency `aya`

### ISSUE THREAD

**Issue by nerdalert** [redhat-et/bpfd#132]
Just posting this as a temporary work around until the following patch is merged in upstream Aya: [aya: Add PinnedProgram](https://github.com/aya-rs/aya/pull/389)

If you get the following when trying to build bfd:

```
$ cargo build
    Updating git repository `https://github.com/dave-tucker/aya`
error: failed to load source for dependency `aya`

Caused by:
  Unable to update https://github.com/dave-tucker/aya?branch=program-from-pinned#1769933b

Caused by:
  object not found - no match for id (1769933b83c3a233a204064245af2ee43dcb2eb3); class=Odb (9); code=NotFound (-3)
```

SImply update the Aya package with the following and then you will be able to build bpfd:

```
cargo update -p aya
```

**Comment by astoycos** [comment]
closed with https://github.com/aya-rs/aya/pull/496
