### ISSUE TITLE
Move bpfd directory/file management out of setup.sh and into code

### ISSUE THREAD

**Issue by Billy99** [redhat-et/bpfd#166]
bpfd cannot guarantee the that the `setup.sh` script is run, so move all the directory creation and chown/chmod to bpfd user and user group out of the `setup.sh` script and into the code.

**Comment by dave-tucker** [comment]
Just a thought, maybe we could also move certificate generation here too (in the case we have a default cert path and the certs don't exist)?
e.g https://github.com/djc/sign-cert-remote/blob/main/src/main.rs

**Comment by dave-tucker** [comment]
See also: https://www.freedesktop.org/software/systemd/man/systemd.exec.html

So ultimately systemd can handle RuntimeDir, StateDir, CacheDir etc.. for us, making sure they are created and owned by the users specified in the unit file. This is awesome for working with systemd, but obviously doesn't help with the non-systemd usecase - i.e local development

**Comment by Billy99** [comment]
@dave-tucker I have most of this work completed for bpfd, directories managed by systemd and creating certs within bpfd if it doesn't exist (not pushed yet). How do we want to handle `bpfctl`? Add a new command, `bpfctl certs` to create the certificate? What about creating `/etc/bpfctl/` and sub-directories as `bpfctl:bpfd` since there is no associated systemd service?

**Comment by Billy99** [comment]
FYI: Added a `bpfctl certs` command that will create a certificate and key. Added a `bpfctl.service` files that is a oneshot service that calls `bpfctl certs` and creates the directories as needed. Still working on some details, like how to kick off automatically from `bpfd.service`.

**Comment by Billy99** [comment]
As an FYI: I missed the link about certs generation above. I pulled the logic from https://github.com/sfackler/rust-openssl/blob/master/openssl/examples/mk_certs.rs.

**Comment by Billy99** [comment]
PR #195 was a follow-up to #191 and completed this issue.
