### ISSUE TITLE
Add bytecode Image URL to bpfctl list

### ISSUE THREAD

**Issue by astoycos** [redhat-et/bpfd#177]
If we originally loaded bytecode via an image we should persist that data somewhere so 

A) We can re-pull from the image repository in restart scenarios (where currently we just used the bytecode dumped on the node)

B) We can report the image URL back to the user in bpfctl  

This is a follow up to https://github.com/redhat-et/bpfd/pull/156 but has a slightly larger scope

**Comment by dave-tucker** [comment]
API change time :tada: 

The `path` field should be renamed `location` and be used as either:
- `file:///absolute/path/to/file/on/filesystem`
- `image://quay.io/bpfd/bytecode:xdp_pass@sha256`

**Comment by astoycos** [comment]
Closed Via #247
