### ISSUE TITLE
Refine Map API

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#18]
Since the map fd over UDS API is here to stay, we want to make sure we get a new fd to send to userspace.
That new fd should only allow map operations that we want... and kernel support for that in unvpriv bpf is landing soon.

Would require some work in Aya to:

1. Call `bpf(BPF_OBJ_GET_INFO_BY_FD)` to populate the map info the `Map` struct
2. Add an API to call `Map::new_fd(flags)`, which would do `bpf(BPF_MAP_GET_FD_BY_ID)` where flags should be an enum that supports `ReadOnly` and `ReadWrite` where the former propagates `BPF_F_RDONLY` and the latter, none.

**Comment by kot-begemot-uk** [comment]
+1 - We should start forming a hierarchy under var including bpfs

**Comment by dave-tucker** [comment]
Yes, the more I think about it, the more pinning all maps to bpffs and using unix acls for permissions is definitely the right choice.
Since #8, we now have authentication for clients - the expectation being that the certificate CN maps to a unix user. I'll be adding code to make that user-id available shortly.
Therefore, the work required to implement this would be as follows:

1. Either mount our own bpf fs in `/var/run/bpfd` OR use `/sys/fs/bpf/bpfd`.
2. Extend the Load API to include map permissions - umask or unix permissions.
3. Come up with a sensible scheme e.g maps have uid: $user and gid:bpfd
4. Implement the necessary code to pin maps on creation, and remove pins on deletion
5. Update the docs to state "if you want to access a map from userspace, set the pinning mode to 1 in your BPF map definition"

**Comment by dave-tucker** [comment]
Also just had a thought. Removing pinned maps on program unload should be optional.
This would be to enable a use-case like migrating data from one map to another.

e.g
1. Unload program which uses `/var/run/bpfd/UUID/MAP_A` - don't remove pinned map.
2. Run migration program that reads data from MAP_A and writes data to MAP_B (outside of bpfd).
3. `rm MAP_A; mv MAP_B MAP_A`
3. Load program again, but using the existing `var/run/bpfd/UUID/MAP_A`

The evolved `GetMap` API could be called before unload of program A, so the program run outside of bpfd for migration could operate on it.
We might need an additional API to support `with_maps_from: UUID`... but that can be added later.

The main reason I brought this up was to ensure we don't make decisions re: dir heirarchy now that we come to regret later

**Comment by kot-begemot-uk** [comment]
Just a clarification - when you say Unix ACLs I assume you mean basic perms. bpfs does not support any fine grain ACLs - those ops are not defined in the file_ops struct.

**Comment by astoycos** [comment]
This was completed in https://github.com/redhat-et/bpfd/pull/42 I believe 

Closing for now feel free to re-open @dave-tucker
