### ISSUE TITLE
Update static program to be on par with bpfctl load

### ISSUE THREAD

**Issue by Billy99** [redhat-et/bpfd#232]
static programs are loaded from a toml file. The syntax/data structures/code need to be on par with the bpfctl load command. In particular:
* Need to be able to load from URL (missing --from-image equivalent)
* Add support for tc and tracepoint program types (only xdp currently supported)
* There is a field `pub attach: Option<String>` that doesn't appear to be used.

**Comment by astoycos** [comment]
I'll probably try and tackle this along with https://github.com/redhat-et/bpfd/issues/177
