### ISSUE TITLE
Section name validation

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#31]
If you pass a bad section name using:
```
sudo ./target/debug/bpfctl load -p xdp -i wlp2s0 -s "invalid" --priority 50 ~/dev/xdp-tutorial/basic01-xdp-pass/xdp_pass_kern.o
```
We return an error, but we never clean up the program metadata.
As a result, a subsequent call with a valid section name will fail, since it's considered a "new" extension, and the old failed one will still fail to load.

We should  `Bpf::load_file(...)` and `bpf.programs_get()` BEFORE we add this to our list extension programs.
We don't need to actually load the program (although we could, and just not attach it)

**Comment by Billy99** [comment]
Fixed by #51
