### ISSUE TITLE
Investigate using GRPC API over Unix Socket

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#317]
This can avoid using the network for communication between bpfd-agent and bpfd just in case a user were to add a filter that blocked communication

**Comment by Molter73** [comment]
Hey there!

I've looked into this briefly and found a great example on having tonic listen to unix sockets here: https://github.com/hyperium/tonic/tree/master/examples/src/uds

I have a few questions on implementation details though:
- I'd assume we want bpfd to always listen on a fixed path (something like `/run/bpfd/bpfd.sock`) and there should be no need to make this configurable, right?
- Do we want to listen both on the unix socket AND a network socket? If so, is it OK to have 2 separate instances of tonic servers? This we would imply we need 2 instances of `BpfLoader` as well, which I assume wouldn't be a major problem, but we could also have a single instance for the Unix socket and have messages from the network socket forwarded to it (I have no idea how we would do this though, I need to look into it if this is the implementation we want).
- What behavior do we want to implement for `bpfctl`? Should it try on the network socket first, then the unix socket if it fails or the other way around? Do we want it to always try the network socket and implement a new `--unix` argument or something of the sort for it to use the unix socket instead?

**Comment by dave-tucker** [comment]
> Hey there!
> 
> I've looked into this briefly and found a great example on having tonic listen to unix sockets here: https://github.com/hyperium/tonic/tree/master/examples/src/uds
> 
> I have a few questions on implementation details though:
> 
> * I'd assume we want bpfd to always listen on a fixed path (something like `/run/bpfd/bpfd.sock`) and there should be no need to make this configurable, right?

I would opt for a configurable path.

> * Do we want to listen both on the unix socket AND a network socket? If so, is it OK to have 2 separate instances of tonic servers? This we would imply we need 2 instances of `BpfLoader` as well, which I assume wouldn't be a major problem, but we could also have a single instance for the Unix socket and have messages from the network socket forwarded to it (I have no idea how we would do this though, I need to look into it if this is the implementation we want).

I'd start with just one, and then look at enabling multiple later.
bpfd has an (undocumented) internal API that keeps RPC implementations away from the mechanics of bpf.
we would ideally spawn tasks for each instance of a listening socket, and share the same channel that sends work to the bpf thread.

We should have some config that choses the socket - ie. `unix:///run/bpfd/bpfd.sock` or `tcp://127.0.0.1:12345` etc.. either in config file or command line flags.

> * What behavior do we want to implement for `bpfctl`? Should it try on the network socket first, then the unix socket if it fails or the other way around? Do we want it to always try the network socket and implement a new `--unix` argument or something of the sort for it to use the unix socket instead?

I would just keep the defaults the same for both server and client, which would be UNIX socket first.
bpfctl also has a config file, so if you change the socket in the server side, you can change it in the client side config too.
