### ISSUE TITLE
Program Persistence

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#33]
Currently, the lifecycle of all `bpf` loaded by `bpfd` is equivalent to the lifetime of the process.
Once `bpfd` dies, all bpf programs are detached and unloaded from the kernel.

For `systemctl restart bpfd`, this behaviour isn't desirable.
We can either:

## Pin all programs, links etc...

Pro: 
- eBPF code continues to run unhindered while the daemon restarts

Con:
- We need to manage additional code to `pin` all objects... and to remove the reference from bpffs when we drop them to avoid leaking resources. Not only that, we also need to rebuild our runtime state using the BPF query APIs - some work may be necessary upstream in Aya to make this possible.

## Persist state to /var/run/bpfd/$iface/$program.toml

Pro:
- Less lifecycle code to maintain as all runtime state can successfully be rebuilt from /var/run

Cons:
- eBPF programs will be unloaded/reloaded

I'm not really sure which option is best as of now.

**Comment by kot-begemot-uk** [comment]
If you pin, you can associate each program + pin with policy. 

As a result on reload ebpfd can kill programs which do not fit the new policy.

If you persist state you IMHO do all of that work and then jump through a few hoops on reload.

Pinning along with metadata for the pin is IMHO the better solution.

**Comment by dave-tucker** [comment]
Right, so we would also want to extend the load-api to include a `restart-policy` which seems like a very neat idea! Thanks
