### ISSUE TITLE
Support patching BPF Program Data

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#338]
Aya's [Bpf::set_global](https://docs.aya-rs.dev/user/aya/struct.bpfloader#method.set_global) should be exposed in the bpfd API to support patching data in .rodata maps BEFORE they are frozen.

From a GRPC standpoint this could be represented as:
```proto3
map<string, bytes> global_data = 7;
```
This may not need to be optional, since an empty map will be fine.

**Comment by astoycos** [comment]
Being used in netobserv -> https://github.com/netobserv/netobserv-ebpf-agent/blob/main/pkg/ebpf/tracer.go#L68

**Comment by astoycos** [comment]
```
so when you issue a load request you’d include something like this in the load-request:
global_data: map[string]interface{}{"direction": 1},
not sure how easy it is from the k8s-api side to include misc k/v pairs, but it must be possible because that’s how - env works in pod specs iirc
```

**Comment by astoycos** [comment]
finished with https://github.com/redhat-et/bpfd/pull/371
