### ISSUE TITLE
security: API Authorization (Access Control)

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#37]
Since #8 the API is restricted to authenticated users.
The process of authentication is to provide $user with a certificate.

Currently the API consists of:
- Load
- Unload
- GetMap

With #36 operations will only be permitted against resources that are owned by the user.
And `GetMap` is likely to be deprecated as pinned map paths can be sent in the `LoadResponse`.

That leaves only 2 APIs that would require authorization and it doesn't seem necessary at this point.
However if we decide to add #9 perhaps there is an argument for restricting the scope of calls made to only permit the loading of certain program types.

**Comment by astoycos** [comment]
Closing as out of scope.
