### ISSUE TITLE
Allow configuration of listening endpoint.

### ISSUE THREAD

**Issue by Molter73** [redhat-et/bpfd#379]
Hey Folks!

I was playing around with bpfd, trying to build and run it and was hit with the following error message:

```
Error = tonic::transport::Error(Transport, hyper::Error(Listen, Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }))
```

The address itself is not used in my system, but I found an [issue](https://github.com/hyperium/tonic/issues/485) with a similar error on tonic (which to my understanding is what tokio uses for grpc and is therefore used by bpfd), suggesting to change the address from `[::1]` to `0.0.0.0`. When I went to do that, I found the address is hardcoded [here](https://github.com/redhat-et/bpfd/blob/e592b47c32db591ef83aed693c86d58be51b5ef8/bpfd/src/lib.rs#L38). No big deal for me, I simply changed it in the code and re-run, but I do think it’d be nice to have a way to configure this, not just as a way to fix the error, but also limit the scope of addresses bpfd binds to without having to re-compile.

I know this would be super low priority, but would be up to create a PR for it if there's interest in this. In my mind we could add something like this to the existing configuration:
```toml
[endpoint]
address = "[::1]"
port = 50051
``` 

We could also do something simpler like merging address and port:
```toml
[endpoint]
address = "[::1]:50051"
``` 

I also apologize if this is something duplicated in some other issue or already addressed in an open PR, I went through them but couldn't find anything that seemed to match this.

**Comment by astoycos** [comment]
Hiya @Molter73 Thanks for opening an issue! :) 

It had been on the list to make this configurable so if you want to open a PR for it that'd be great! I think 

```
[grpc.endpoint]
address = "[::1]:50051"
```
would be perfectly fine syntax. Just be sure to also fix the [hard-coded address in `bpfctl`](https://github.com/redhat-et/bpfd/blob/main/bpfctl/src/main.rs#L108) as well.

**Comment by Molter73** [comment]
Well I can't find a way to tell serde to surface a nested field, think I'll just open the PR as is and maybe someone more knowledgeable than me will point me in the right direction.

Two more questions before I open the PR though:
- I see there's a (seemingly unused) `bpfd/src/config.rs` and a `bpfd-api/src/config.rs`. Updating the latter seems to be enough for the change to work, should I duplicate the change on the other one for consistency?
- I haven't looked at what documentation would need to be updated, I'll look into it, but any pointers are appreciated 🙂
