### ISSUE TITLE
Deployment on K8s

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#46]
We should consider (and implement) the best way of deploying bpfd in a k8s environment.

1. A user would install `bpfd-operator` which would add a CRD that lets K8s users submit BPF programs to be loaded
1. The operator would install a new component `bpfd-agent` via a `DaemonSet`. `bpfd-agent` would be a K8s controller that watches for changes in the CRD, and (if applicable) uses bpfd's GRPC API to perform the operations against `bpfd` on the host.

Open questions:

1. Is `bpfd` installed on the host (i.e via `rpm`) or is it a running in a `DaemonSet` - or can we support both models?
1. Can we re-use the `TOML` config file format described in #30 for this?
1. Does `bpfd` somehow need to tag resources that are managed by k8s - i.e in case of controller restart/upgrade so it can re-compute it's state.

**Comment by astoycos** [comment]
Some thoughts here...

1. So if we wanted to install/ run as a true system daemon this would need to be done through the [Openshift Machine Config Operator](https://github.com/openshift/machine-config-operator) I believe, It might be quicker to deploy it as a daemonset to start 

2. We might just need to convert this to YAML or have some shim that translates static programs defined in YAML to toml 

3. The operator _should_ take care of this right?  Lets say we have a new CRD type called `xdp_program` that defines a given program, when/ if the daemonset is forced to restart the operator will ensure the programs are configured/loaded

**Comment by astoycos** [comment]
Starting on this... I'll post questions/ answers as we go along: 

To start I'm not 100% sure how we'll deal with CERTs for bpfd/ any clients we'll use yet that's TBD 

Also need to figure out if the operator should just use bpfctl to load programs or a rust grpc client (I'm leaning towards the latter currently)

**Comment by astoycos** [comment]
Another question... How/ where should users dump compiled bpf bytecode? Or should we allow the operator to be able to compile it for us?

**Comment by dave-tucker** [comment]
> To start I'm not 100% sure how we'll deal with CERTs for bpfd/ any clients we'll use yet that's TBD

Maybe the operator can provision certs for bpfd/bpfctl on each node?

> Also need to figure out if the operator should just use bpfctl to load programs or a rust grpc client (I'm leaning towards the latter currently)

I was thinking you'd have a `bpfd-agent`, that has been given a cert to permit it to talk to bpfd on that node.

> How/ where should users dump compiled bpf bytecode? Or should we allow the operator to be able to compile it for us?

Input is always compiled bytecode. What you could do is distribute this across the cluster - not sure how - and add a programs entry to `programs.d` then send the bpfd daemon a `SIGHUP` -per #91 - or just restart it for now.

**Comment by dave-tucker** [comment]
Oh, container images might be a fun way of shipping bytecode :wink:
