### ISSUE TITLE
packaging: Investigate rust2rpm

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#5]
https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/

We should build RPMs in CI that we can use for testing...

**Comment by dave-tucker** [comment]
I just also thought that it's not just a case of binaries being in place... but also a unit file for systemd.

**Comment by dave-tucker** [comment]
Ok this looks like it's blocked on #11.
We can't use `rust2rpm` because it relies on source being available on crates.io.
We can't publish to `crates.io` because we have a `[patch.crates-io]` in `Cargo.toml`

**Comment by dave-tucker** [comment]
```
[Unit]
Description="bpfd loading daemon"
After=network.target

[Service]
ExecStart=/usr/sbin/bpfd
MemoryAccounting=true
MemoryLow=infinity
MemoryMax=infinity
User=bpfd
Group=bpfd
AmbientCapabilities=CAP_BPF CAP_NET_ADMIN CAP_SYS_RESOURCE
CapabilityBoundingSet=CAP_BPF CAP_NET_ADMIN CAP_SYS_RESOURCE
```

Sample Unit File :point_up:

**Comment by nerdalert** [comment]
Quick updated, started looking into this and though there does seem to be a claim workspaces are supported by `rust2rpm` I'm not seeing it when trying it on the workspace bpfd Cargo file.

e.g.
```
rust2rpm /home/brent/bpfd/
Subcommand failed with code 101: cargo read-manifest --manifest-path=/home/brent/bpfd/Cargo.toml
```

Now if you run it on a workspace member such as bpfdctl it does generate a sepc file. ¯\_(ツ)_/¯ 

Worst case we just generate a spec file manually. Will update as I make progress. Ty!

**Comment by dave-tucker** [comment]
@nerdalert Yeah for now I'd focus on getting the unit file checked in so we can manually start/stop bpfd as a system service:
https://docs.fedoraproject.org/en-US/packaging-guidelines/Systemd/

The other complication is certificates. We *may* need to include generation code in bpfd (instead of via bash script).
I'm not sure how Docker handles this (maybe unsecure by default?) but I would hope there are other daemons that can generate their own self-signed certs if none are provided.

I'll do a release to `crates.io` as soon as #11 is merged which will make using `rust2rpm` much easier - no paths required.

**Comment by dave-tucker** [comment]
Either way the requirement of "generate RPMs for use in testing" won't be met. But we could probably set up an install script that puts the binaries, config etc.. in the right place using something like `vagrant` to stand up a test machine like in #22... and RPMs would only be made for release builds.
