### ISSUE TITLE
Multiprog for TC

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#9]
The dispatcher code is already written but hasn't been tested. We can already attach multiple programs to a TC hook but having deterministic ordering using a dispatcher seems a better option - I think. Either way we should investigate whether a dispatcher is necessary, or whether the existing mechanism in kernel can be tamed.

**Comment by dave-tucker** [comment]
The dispatcher code is in the git history for whomever picks this up - not in current tree on `main`.

Basically we need to do some investigation...
Once you've attached a qdisc to an interface, how easy is it to get the ordering right using classid or flowids?
Some reading of `man tc-bpf` will be required.
This can be prototyped using https://github.com/redhat-et/net-ebpf-playground and maybe some `bpf_trace_printk` to see which program gets triggered and in what order.

Once done, we'll need to know:

1. Does Aya have the right API for [attach?](https://docs.rs/aya/latest/aya/programs/tc/struct.SchedClassifier.html#method.attach)
2. A plan for how to implement the ~same API as we have for XDP programs, for TC. For example, some constructs (`chain_call_actions`) may not be portable

**Comment by anfredette** [comment]
I documented the behavior here: https://gist.github.com/anfredette/732eeb0fe519c8928d6d9c190728f7b5

**Comment by anfredette** [comment]
@dave-tucker, should we close this one out as investigation completed, and then open one (or more) for implementing the support?  I suspect there will be multiple phases for the implementation.  There are some limitations in the current aya support, but I think they are sufficient at least for an initial implementation.

**Comment by dave-tucker** [comment]
Makes sense
