### ISSUE TITLE
Using CNI images to ship eBPF bytecode

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#99]
It should be relatively easy to do using [oci-rs](https://github.com/containers/oci-spec-rs).

1. Define the rules that images should conform to. At the minimum we'll need an annotation/label to identify this as eBPF.
We may want to add optional labels/annotations to include API defaults - like `program_section` etc.. - but we would also need to document how these can be overridden.
2. Create an image repository: `/var/lib/bpfd/images`
3. Add the ability for `bpfd` to pull an image from a registry and extract the bytecode from the rootfs.
4. As a bonus we might want to consider integration with cosign to prevent the load of unsigned images.

**Comment by astoycos** [comment]
I can take a stab at this as I investigate operator development but if anyone gets time before me feel free to pick it up!

**Comment by dave-tucker** [comment]
Fixed in #102
